services:
  fire-rules-api:
    image: ghcr.io/dyoun/rules-engine:latest
    container_name: fire-rules-api
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - FLASK_ENV=production
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

  rails-app:
    build: .
    container_name: obsv-admin-rails
    ports:
      - "3000:3000"
    environment:
      - RAILS_ENV=development
      - DATABASE_URL=postgresql://postgres:password@obsv-admin-db:5432/obsv_admin_development
      - RULES_ENGINE_URL=http://fire-rules-api:5000
    depends_on:
      - postgres
    volumes:
      - .:/rails
      - bundle_cache:/usr/local/bundle
    restart: unless-stopped

  postgres:
    image: postgres:16
    container_name: obsv-admin-db
    environment:
      - POSTGRES_DB=obsv_admin_development
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
  bundle_cache: