version: '3.8'

services:
  # PostgreSQL database
  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: rules_admin_production
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Fire Rules Engine API (Flask)
  fire-rules-api:
    image: ghcr.io/dyoun/fire-rules-eng:latest
    ports:
      - "5001:5000"
    environment:
      - FLASK_ENV=production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Rails Observation Admin App
  web:
    image: ghcr.io/dyoun/obsv-admin:latest
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://postgres:password@db:5433/rules_admin_production
      RAILS_ENV: development
      RULES_ENGINE_URL: http://localhost:5001
    depends_on:
      db:
        condition: service_healthy
      fire-rules-api:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  postgres_data: